data_augment:
- ALONG_AXIS_LIST:
  - x
  NAME: random_world_flip
- NAME: random_world_rotation
  WORLD_ROT_ANGLE:
  - -0.78539816
  - 0.78539816
- NAME: random_world_scaling
  WORLD_SCALE_RANGE:
  - 0.95
  - 1.05
fusion:
  args: []
  core_method: IntermediateFusionDataset
loss:
  args:
    cls_weight: 1.0
    reg: 2.0
  core_method: point_pillar_loss
lr_scheduler:
  core_method: cosineannealwarm
  epoches: 60
  lr_min: 2.0e-05
  warmup_epoches: 10
  warmup_lr: 0.0002
model:
  args:
    anchor_number: 2
    backbone_fix: false
    base_bev_backbone:
      layer_nums:
      - 3
      - 5
      - 8
      layer_strides:
      - 2
      - 2
      - 2
      num_filters:
      - 64
      - 128
      - 256
      num_upsample_filter:
      - 128
      - 128
      - 128
      upsample_strides:
      - 1
      - 2
      - 4
    compress:
      anchor_nums: 2
      comm_volume: 25
      dim: 256
      method: single
      output_dim: 64
      threshold: false
    compression: 0
    ermvp_fusion:
      agent_size: 5
      depth: 3
      dim_head: 32
      drop_out: 0.1
      input_dim: 256
      mask: true
      mlp_dim: 256
      window_size:
      - 4
      - 4
      - 4
    late_fusion:
      gaussian_smooth:
        c_sigma: 1.0
        k_size: 5
    lidar_range: &id001
    - -140.8
    - -38.4
    - -5
    - 140.8
    - 38.4
    - 3
    max_cav: 5
    pillar_vfe:
      num_filters:
      - 64
      use_absolute_xyz: true
      use_norm: true
      with_distance: false
    point_pillar_scatter:
      grid_size: !!python/object/apply:numpy.core.multiarray._reconstruct
        args:
        - !!python/name:numpy.ndarray ''
        - !!python/tuple
          - 0
        - !!binary |
          Yg==
        state: !!python/tuple
        - 1
        - !!python/tuple
          - 3
        - !!python/object/apply:numpy.dtype
          args:
          - i8
          - false
          - true
          state: !!python/tuple
          - 3
          - <
          - null
          - null
          - null
          - -1
          - -1
          - 0
        - false
        - !!binary |
          wAIAAAAAAADAAAAAAAAAAAEAAAAAAAAA
      num_features: 64
    shrink_header:
      dim:
      - 256
      input_dim: 384
      kernal_size:
      - 3
      padding:
      - 1
      stride:
      - 2
    voxel_size: &id002
    - 0.4
    - 0.4
    - 8
  core_method: pointpillarwhat2keep
name: point_pillar_what2keep
optimizer:
  args:
    eps: 1.0e-10
    weight_decay: 0.0001
  core_method: Adam
  lr: 0.001
postprocess:
  anchor_args:
    D: 1
    H: 192
    W: 704
    cav_lidar_range: *id001
    feature_stride: 4
    h: 1.56
    l: 3.9
    num: 2
    r:
    - 0
    - 90
    vd: 8
    vh: 0.4
    vw: 0.4
    w: 1.6
  core_method: VoxelPostprocessor
  gt_range: *id001
  max_num: 100
  nms_thresh: 0.15
  order: hwl
  target_args:
    neg_threshold: 0.45
    pos_threshold: 0.6
    score_threshold: 0.25
preprocess:
  args:
    max_points_per_voxel: 32
    max_voxel_test: 70000
    max_voxel_train: 32000
    voxel_size: *id002
  cav_lidar_range: *id001
  core_method: SpVoxelPreprocessor
root_dir: /home/zzbhhh/dataset/OpenCOOD/train
train_params:
  batch_size: 2
  epoches: 60
  eval_freq: 2
  max_cav: 5
  save_freq: 2
validate_dir: /home/zzbhhh/dataset/OpenCOOD/test/test
wild_setting:
  async: False
  async_overhead: 0
  backbone_delay: 10
  data_size: 1.06
  loc_err: false
  ryp_std: 0
  seed: 20
  transmission_speed: 27
  xyz_std: 0
yaml_parser: load_point_pillar_params
